### ISSUE TITLE
Dependencies order

### ISSUE THREAD

**Issue by elboulangero** [Debian/dh-make-golang#121]
dh-make-golang sorts `${misc:Depends}` first, while running plain old `wrap-and-sort` put it at the end.

Seems like golang is right if we consider that: https://en.wikipedia.org/wiki/ASCII#Printable_characters (dollar comes first).

OTOH I don't think that we can change how wrap-and-sort works... or maybe we can?

**Comment by anthonyfok** [comment]
Good question!

`/usr/bin/wrap-and-sort` is a Python script, and Python's built-in `sorted()` function puts the `$` dollar first too.

```python
>>> sorted(["golang-github-google-wire-dev", "${misc:Depends}"])
['${misc:Depends}', 'golang-github-google-wire-dev']
```

It turns out that `wrap-and-sort` placing `${xxxx:yyyyyyy}` at the end is a deliberate behavioural change in 2013:

> wrap-and-sort: Put special entries (variables and placeholders) at the end of the list.
> https://salsa.debian.org/debian/devscripts/commit/a48b4e6c846e301fa12da2c111cc51cedc0604e3

And cme libconfig-model-dpkg-perl followed suit in Dec 2017:

> sort dependencies like wrap-and-sort
> https://salsa.debian.org/perl-team/modules/packages/libconfig-model-dpkg-perl/commit/a19752b315ec9287229bc9cc6da7aed6ae698a1b

So I guess dh-make-golang can follow suit too!

**Comment by elboulangero** [comment]
Thanks for your feedback, see #123 then
