### ISSUE TITLE
Make error loud and fatal if debian/ is in upstream sources

### ISSUE THREAD

**Issue by paultag** [Debian/dh-make-golang#2]
`2015/07/26 16:56:50 Could not create debian/ from templates: mkdir ${PATH}: file exists`

(but still creates the target folder, with a `debian/*` populated with upstream bits)

**Comment by paultag** [comment]
Meh. This is actually not trivial, since it works in CWD; I guess it's not the worst thing. It'd be good to get `log.Fatalf` output red (at least) :) (or something). Thoughts?

**Comment by stapelberg** [comment]
Can you give me the package which contains debian/ in its upstream so that I can test for myself what happens here please?

What do you think about ignoring debian/ from upstream sources (with a warning)? After all, by using dh-make-golang, your intention must be to _generate_ debian/, not use someone else’s debian/.

**Comment by paultag** [comment]
@stapelberg it's one of mine - this is a corner case - `dh-make-golang pault.ag/go/dictd`

I think ignoring it with a warning and purging it is perhaps the right thing - just makes the git vcs import a bit more fiddly
