### ISSUE TITLE
FTBFS due to usage of deprecated dependency

### ISSUE THREAD

**Issue by upils** [Debian/dh-make-golang#200]
dh-make-golang is failing to build from source. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1043070

This is due to `golang.org/x/tools/go/vcs` being deprecated and removed from the `tools` pkg (see https://go-review.googlesource.com/c/tools/+/159818/4).

According to the aforementioned change, the recommended way is to use `go list -json`, which would require rewriting parts of the code.

Another solution would be to pin the version of `golang-golang-x-tools` to an older version. But in debian the previous stable version is [0.5.0](https://packages.debian.org/source/stable/golang-golang-x-tools) which is a bit old.

**Comment by anthonyfok** [comment]
@upils Thank you so much for investigating this FTBFS and suggesting the use of `go list -json` as solution.

I hope I will have time to look at it soon, but probably not earlier than end of 2023.
If anyone else has the capacity, you are more than welcome to help fix this issue.

Many thanks!

**Comment by myhro** [comment]
I debugged this issue today and it doesn't look like `go list -json` is a proper replacement for the `golang.org/x/tools/go/vcs` package. At least not for the functionality provided by `vcs.RepoRootForImportPath()`, which [is used in multiple places][1].

Looking at the [examples in the tests][2], it's not possible to figure, for instance, the repository root for the `github.com/google/go-github/v38` module:

1. By default it is treated as a package and can't be found:

```
$ go list -json github.com/google/go-github/v38
no required module provides package github.com/google/go-github/v38; to add it:
        go get github.com/google/go-github/v38
```

2. Looking for the actual package (the one in the `import` statements) yields a bit more information, but none of that refers to the repository root:

```
$ go list -json github.com/google/go-github/v38/github | grep github.com
        "Dir": "/home/myhro/go/pkg/mod/github.com/google/go-github/v38@v38.1.0/github",
        "ImportPath": "github.com/google/go-github/v38/github",
        "Root": "/home/myhro/go/pkg/mod/github.com/google/go-github/v38@v38.1.0",
                "Path": "github.com/google/go-github/v38",
                "Dir": "/home/myhro/go/pkg/mod/github.com/google/go-github/v38@v38.1.0",
                "GoMod": "/home/myhro/go/pkg/mod/cache/download/github.com/google/go-github/v38/@v/v38.1.0.mod",
(...)
```

3. Running it with `-m`, to list modules instead of packages, also doesn't help:

```
$ go list -json -m github.com/google/go-github/v38
{
        "Path": "github.com/google/go-github/v38",
        "Version": "v38.1.0",
        "Time": "2021-08-11T14:26:33Z",
        "Dir": "/home/myhro/go/pkg/mod/github.com/google/go-github/v38@v38.1.0",
        "GoMod": "/home/myhro/go/pkg/mod/cache/download/github.com/google/go-github/v38/@v/v38.1.0.mod",
        "GoVersion": "1.16"
}
```

The examples above were done using `go version go1.21.5 linux/amd64` from `sid`.

I also checked if `go get` has any flags to resolve the root repository for a module, given that accessing https://github.com/google/go-github/v38 directly returns a `404 Not Found`, but haven't find anything helpful in the CLI.

What do you think it would be a reasonable solution? Vendor the whole `golang.org/x/tools` module for now? Copy just the `vcs` package parts we are interested in?

[1]: https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2FDebian%2Fdh-make-golang%24%40e701253+vcs.RepoRootForImportPath&patternType=standard&sm=1&groupBy=path
[2]: https://github.com/Debian/dh-make-golang/blob/e701253f75eabdea1c40644f50b7774ad0115113/check_depends_test.go#L98-L100

**Comment by anthonyfok** [comment]
Thank you @myhro for your help!

For testing on GitHub (where Go module is on), `go mod tidy` automatically picked up:
```
golang.org/x/tools/go/vcs v0.1.0-deprecated
```
so `go build` still works, good for dh-make-golang development/maintenance until we find a good alternative.

As for Debian packaging where GO111MODULE=off, I have used a way to _sneak in_ Go packages, so I think I'll do that for dh-make-golang 0.7.0-1.

Cheers!
