### ISSUE TITLE
"use of internal package not allowed" running dh-make-golang

### ISSUE THREAD

**Issue by tpot** [Debian/dh-make-golang#50]
I'm running `dh-make-golang` to grab the source for a new snapshot
of containerd, and get the following error:

```
# dh-make-golang -git_revision 0366d7e github.com/docker/containerd
2016/11/16 14:02:29 Downloading "github.com/docker/containerd/..."
go get: 202.79 MiB
package github.com/docker/containerd/vendor/src/golang.org/x/net/trace
	imports golang.org/x/net/internal/timeseries: use of internal package not allowed
package github.com/docker/containerd/vendor/src/google.golang.org/grpc
	imports google.golang.org/grpc/internal: use of internal package not allowed
2016/11/16 14:12:26 Could not create a tarball of the upstream source: exit status 1
```

It looks like the vendored dependencies that have internal packages, x-net and golang-grpc,
here are trying to be imported while being built using a longer package name: `github.com/docker/containerd/vendor/src/google.golang.org/grpc` vs `google.golang.org/grpc`
but I don't understand why.

My guess is that this was always happening but only now produces an error as upstreams
are only just starting to add internal packages to their code.

**Comment by stapelberg** [comment]
This issue happens because:

1. dh-make-golang is running `go get github.com/docker/containerd/...` (note the `/...` at the end)
2. docker/containerd has vendored copies of libraries in vendor/src instead of vendor/. As per https://github.com/golang/go/wiki/PackageManagementTools, this implies that they are using `gb` for vendoring. I think `gb` requires users to use `gb` to build, but I might be wrong.
3. That said, even when moving vendor/src/* to vendor/ (so that Go will correctly interpret `internal` paths), we run into an error: `vendor/github.com/Microsoft/go-winio/file.go:45: undefined: syscall.Overlapped`

I’m not entirely sure yet what a good fix would be.

**Comment by stapelberg** [comment]
@Merovius pointed out that `gb` and the `go` tool are just fundamentally incompatible. Internal packages and canonical import paths are implemented in the `go` tool.

I think there are a couple of options, in order of success likelihood/personal preference:

 1. Ask docker/containerd to use a vendoring tool which plays nice with the `go` tool.
 2. Ask the `gb` authors to make their tool play nice with the `go` tool.
 3. Declare Go libraries using `gb` out of scope for `dh-make-golang` :(.
 4. Add `gb` support as a special case to `dh-make-golang` (before we do this, we should look at whether any other vendoring tool would also require special support, and how much the different vendoring tools are used by the community respectively).

**Comment by Merovius** [comment]
Maybe @davecheney has opinions/tips?

**Comment by stapelberg** [comment]
Commit 99a238019b5a2bdc0d3d2bad5f93b280a49eedcd also fixed this issue, or at least I can now run `dh-make-golang github.com/docker/containerd` without problems :).
