### ISSUE TITLE
Modify code that scrapes people.d.o to use the binary apt index directly

### ISSUE THREAD

**Issue by paultag** [Debian/dh-make-golang#9]
go-debian can do this (actually, helper methods in go-resolver can make it even easier!)

http://godoc.org/pault.ag/go/resolver#GetBinaryIndex
http://godoc.org/pault.ag/go/debian/control#BinaryIndex

If you want to wait until it's more mature, that's fine too. I just noticed a typo in a type name. D'oh.

**Comment by paultag** [comment]
(Or better yet, use the Sources index and grab packages list for each!)

**Comment by stapelberg** [comment]
The motivation to use a preprocessed file is to save bandwidth and time and to always have a sufficiently up-to-date index instead of requiring users to update their index before running the tool.

What’s the motivation for using the apt index directly?

**Comment by paultag** [comment]
@stapelberg a few points --

  * It uses *less* bandwidth, since you can use the local apt indexes in `/var/lib`.
  * This would work for derivatives and personal repos, rather than hardcoding a grep on a cron for the archive
  * It's more up to date (if your cron goes dead or you're off making wine without internet while master.d.o gets updated)

**Comment by stapelberg** [comment]
> This would work for derivatives and personal repos, rather than hardcoding a grep on a cron for the archive

That’s definitely a fair point. Maybe we should check whether we’re running on Debian instead of a derivative and only then use the online version.

> It's more up to date (if your cron goes dead…

I see how a cronjob is not the most reliable way, but I think it trumps local indexes for many use-cases.

> or you're off making wine without internet while master.d.o gets updated)

I think adding a fallback to local indexes is fine.

> It uses less bandwidth, since you can use the local apt indexes in /var/lib.

As explained before, I question whether local indexes are up-to-date. I know that at least on my system, they aren’t until I need them to be. I also don’t think the bandwidth usage of querying the file is a concern, whereas running a full apt-get update often amounts to dozens of megabytes, which easily becomes a concern.

**Comment by stapelberg** [comment]
I’ll close this as obsolete in favor of #73, which is a superior solution to either approach discussed in this issue, as it is derived directly from the source of truth, with no delay.
